### ISSUE TITLE
Feature requests (custom port, proto, etc.)

### ISSUE THREAD

**Issue by francoism90** [graysky2/ovpngen#1]
```
client
dev tun
proto udp # or tcp
remote example.com 1194 udp # e.g. 443
resolv-retry infinite
nobind
user nobody # Doesn't work on Windows, but should work on Linux
group nobody # same as above
persist-key
persist-tun
verb 3
comp-lzo
remote-cert-tls server
key-direction 1
```

Many thanks for creating this script, works perfectly on my setup. :)

**Comment by graysky2** [comment]
I toyed with adding additional switches but at some point it becomes nonsensical in that you can just edit the ovpn file when finish with minor tweak and changes.  The important part adding the certs/keys in the correct order.

**Comment by graysky2** [comment]
Changed my mind, enjoy!https://github.com/graysky2/ovpngen/commit/6cb509829669be4eed315a32195cafc2cd8db1d0

**Comment by francoism90** [comment]
Many thanks! :)
