### ISSUE TITLE
Compress missing lz4-v2

### ISSUE THREAD

**Issue by francoism90** [graysky2/ovpngen#3]

**Comment by graysky2** [comment]
...a little more detail would be helpful.

https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf#L257
https://github.com/OpenVPN/openvpn/blob/master/sample/sample-config-files/server.conf#L258

If both those lines are defined in the server config, one does not need to specify anything in the client config (ie no comp* line is needed).  In my testing, one can actually define `comp-lzo` in the client config and it is overridden by the server (ie lz4 is used per the client log).
